<?xml version="1.0" encoding="UTF-8"?>
<!--Bancololombia - Gerencia Desarrollo Servicios de Integracion - 01/11/2018 - Generado por: luis  -->
<wsdl:definitions name="ConsultaCreditoConstructor"
	targetNamespace="http://grupobancolombia.com/intf/Producto/CreditoHipotecario/ConsultaCreditoConstructor/Enlace/V1.0" 
	xmlns:tns="http://grupobancolombia.com/intf/Producto/CreditoHipotecario/ConsultaCreditoConstructor/Enlace/V1.0"
	xmlns:ns="http://grupobancolombia.com/intf/Producto/CreditoHipotecario/ConsultaCreditoConstructor/V1.0" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">

	<wsdl:import location="ConsultaCreditoConstructor_Intf_V1.0.wsdl"
		namespace="http://grupobancolombia.com/intf/Producto/CreditoHipotecario/ConsultaCreditoConstructor/V1.0">
	</wsdl:import>

	<wsdl:binding name="ConsultaCreditoConstructorHttpBinding" type="ns:ConsultaCreditoConstructor">

		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http" />


		<wsdl:operation name="consultarSaldoProoyectosConstructor">

			<soap:operation
				soapAction="http://grupobancolombia.com/intf/Producto/CreditoHipotecario/ConsultaCreditoConstructor/V1.0/consultarSaldoProoyectosConstructor" />

			<wsdl:input name="consultarSaldoProoyectosConstructorRequest">
			
				<soap:body parts="parameters" use="literal" />
			
				<soap:header message="ns:consultarSaldoProoyectosConstructorRequestMsg" part="requestHeader" use="literal" />
			
			</wsdl:input>

			<wsdl:output name="consultarSaldoProoyectosConstructorResponse">
			
				<soap:body parts="result" use="literal" />
			
				<soap:header message="ns:consultarSaldoProoyectosConstructorResponseMsg" part="responseHeader" use="literal" />
			
			</wsdl:output>

			<wsdl:fault name="systemException">
				<soap:fault name="systemException" use="literal" />
			</wsdl:fault>
			<wsdl:fault name="businessException">
				<soap:fault name="businessException" use="literal" />
			</wsdl:fault>


		</wsdl:operation>



	</wsdl:binding>

	<wsdl:service name="ConsultaCreditoConstructor">
		<wsdl:port binding="tns:ConsultaCreditoConstructorHttpBinding" name="ConsultaCreditoConstructorHttpPort">
			<soap:address
				location="http://grupobancolombia.com/intf/Producto/CreditoHipotecario/ConsultaCreditoConstructor/Enlace/V1.0" />
		</wsdl:port>
	</wsdl:service>

</wsdl:definitions>